# Generated by Django 5.0.6 on 2024-06-25 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_topic_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
